### ISSUE TITLE
Add multiple missions

### ISSUE THREAD

**Issue by ghermans** [FiveM-Scripts/venomous-freemode#9]
## Todo
- [X] Select and start missions by using vf_phone (**Play Quick Job**)
- [ ]  Complete Alien Slasher
- [ ]  Complete Dispatch
- [ ] Complete Runner Madness
- [x] Complete Snitch
- [ ] Add cash amount to the player once the mission is completed.
- [ ] Test the missions before pushing the release.
